import axios from 'axios';
import fs from 'fs';
import path from 'path';

export interface DiscordSendParams {
  botToken: string;
  channelId: string;
  applicantName: string;
  applicantEmail: string;
  companyName: string;
  websiteUrl: string;
  pdfPath: string;
}

export class DiscordService {
  /**
   * Uploads the PDF report and sends applicant details to a Discord channel
   */
  async sendReport(params: DiscordSendParams): Promise<void> {
    const {
      botToken,
      channelId,
      applicantName,
      applicantEmail,
      companyName,
      websiteUrl,
      pdfPath,
    } = params;

    if (!botToken || !channelId) {
      throw new Error('Discord Bot Token and Channel ID must be configured in settings.');
    }

    if (!fs.existsSync(pdfPath)) {
      throw new Error(`PDF report file not found at: ${pdfPath}`);
    }

    const fileName = path.basename(pdfPath);
    const fileBuffer = fs.readFileSync(pdfPath);

    // Create a multipart form using Node 20+ native FormData & Blob
    const formData = new FormData();

    // Prepare Discord rich message embed
    const payload = {
      content: `🔔 **New Research Report Submission**`,
      embeds: [
        {
          title: `Research Report: ${companyName}`,
          description: `Company intelligence report generated by **Relu Consultancy Research Assistant**.`,
          color: 15380232, // Gold/Amber (#eab308 in decimal)
          fields: [
            {
              name: 'Company Website',
              value: websiteUrl || 'Not provided',
              inline: true,
            },
            {
              name: 'Applicant Name',
              value: applicantName || 'Not provided',
              inline: true,
            },
            {
              name: 'Applicant Email',
              value: applicantEmail || 'Not provided',
              inline: true,
            },
          ],
          timestamp: new Date().toISOString(),
          footer: {
            text: 'AI Research Assistant',
          },
        },
      ],
    };

    formData.append('payload_json', JSON.stringify(payload));

    // Append file as a Blob with filename
    const pdfBlob = new Blob([fileBuffer], { type: 'application/pdf' });
    formData.append('files[0]', pdfBlob, fileName);

    try {
      await axios.post(
        `https://discord.com/api/v10/channels/${channelId}/messages`,
        formData,
        {
          headers: {
            'Authorization': `Bot ${botToken}`,
            // Content-Type is set automatically by Axios with correct boundary
          },
        }
      );
    } catch (error: any) {
      console.error('Discord API Error:', error.response?.data || error.message);
      const apiMsg = error.response?.data?.message || error.message;
      throw new Error(`Discord upload failed: ${apiMsg}`);
    }
  }
}
